method: onet
data:
  input_type: voxels
  path: occupancy_networks/data/ShapeNet
  dim: 3
  points_subsample: 1024
  classes: ["03001627", ]
model:
  encoder_latent: simple
  decoder: cbatchnorm
  encoder: voxel_simple
  c_dim: 256
  z_dim: 128
training:
  out_dir: occupancy_networks/out/voxels/onet_chair_latent
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 0
test:
  threshold: 0.20
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1