method: onet
data:
  input_type: voxels
  path: occupancy_networks/data/ShapeNet
  dim: 3
  points_subsample: 1024
  classes: ["04379243", ]
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: voxel_simple
  c_dim: 256 
  z_dim: 0
training:
  out_dir:  occupancy_networks/out/voxels/onet_table
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 0
  validate_every: 2000
test:
  threshold: 0.01
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
